name: Heart On Your Sleeve

on:
  workflow_dispatch: {}

jobs:
  react-and-close:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue, react ❤️ and close
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Temp reaction issue',
              body: 'Temporary issue created by workflow to add a heart reaction.'
            });
            // add reaction (content can be: +1, -1, laugh, confused, heart, hooray, rocket, eyes)
            await github.rest.reactions.createForIssue({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issue.data.number, content: 'heart' });
            await github.rest.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issue.data.number, state: 'closed' });
